# Generated by Django 5.0.6 on 2024-07-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/media/uploads/')),
                ('borrowing_price', models.IntegerField()),
                ('user_reviews', models.TextField()),
                ('category', models.ManyToManyField(to='books.category')),
            ],
        ),
    ]
