# Generated by Django 5.0.6 on 2024-07-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Books',
        ),
    ]
