# Generated by Django 5.0.6 on 2024-07-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='book',
        ),
    ]
