# Generated by Django 5.0.6 on 2024-08-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_borrowedbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user_reviews',
        ),
    ]
