# Generated by Django 5.0.6 on 2024-07-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_remove_account_user_userbankaccount'),
        ('transactions', '0004_transaction_balance_after_transaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
